version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: fastapi-fish
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    env_file:
      - src/.env
    depends_on:
      - redis

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: celery-fish
    command: celery -A main.celery_ worker -l info --pool=eventlet
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: celery-fish-flower
    command: celery --broker=redis://redis:6379/0 -A main.celery_ flower --port=5566
    ports:
      - 5566:5566
    depends_on:
      - redis