name: Test-in

on:
  push:
    branches: [patch, master]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - run: docker-compose -f docker-compose.yaml build --no-cache
    - run: curl -X GET http://127.0.0.1/
